VKTokenFile: "$HOME/interLink/token"
InterlinkURL: "https://intertwin.vega.izum.si"
SidecarURL: "http://intertwin.vega.izum.si"
InterlinkPort: "30443"
SidecarService: "slurm" #docker, slurm
SbatchPath: "/usr/bin/sbatch"
ScancelPath: "/usr/bin/scancel"
CommandPrefix: ""
ExportPodData: true
DataRootFolder: ".knoc"
ServiceAccount: "knoc"
Namespace: "vk"
Tsocks: false
TsocksPath: "$WORK/tsocks-1.8beta5+ds1/libtsocks.so"
TsocksLoginNode: "login01"